### ISSUE TITLE
How to exclude certain filetype?

### ISSUE THREAD

**Issue by Kamilius** [brigade/haml-lint#78]
Hi. In my project I use unobstrusive javascript with Ruby on Rails. While linting *.js.haml files, they give constant "UnnecessaryStringOutput" errors.
Is there a way to exclude this filetype from being linted at all?
Currently tried to use exclude next way in my .haml-lint.yml:

```yml
UnnecessaryStringOutput:
    enabled: true
    exclude:
      - *.js.haml (or /*.js.haml/, or '*.js.haml', or this exclude right under 'skip_frontmatter' parameter)
```

None of those tries gave a positive result.
Please help me to solve this issue.
Thanks

**Comment by sds** [comment]
Hey @Kamilius,

The glob you wrote will only exclude files in the root directory. You need to write:

```yaml
linters:
  UnnecessaryStringOutput:
    exclude:
      - '**/*.js.haml'
```

...in order to exclude all `.js.haml` files in any directory. (similar to the `eslint` and `rubocop` projects)

**Comment by Kamilius** [comment]
@sds, thanks a lot! :)

**Comment by gajmar** [comment]
@sds 
Hi! I copied your snippet to .haml-lint.yml and exclusion doesn't work, but when when I add --exclude "**/*.js.haml" to command everything works great.
Could you know what can be the reason?
Thanks

**Comment by sds** [comment]
Hey @gajmar,

The example I provided will only exclude `UnnecessaryStringOutput` lints. Specifying the `--exclude` flag will exclude _all_ lints for the files matches by the exclude pattern.

Are you sure the lints you are seeing are `UnnecessaryStringOutput` lints? If you want to exclude all lints, you should add the following to your `.haml-lint.yml` file (and make sure you're running `haml-lint` in the same directory as that file):

```yaml
exclude:
  - '**/*.js.haml'
```

**Comment by gajmar** [comment]
Hey, @sds 
yes it is definitely UnnecessaryStringOutput lint.
```
app/views/users/tracked/videos/create.js.haml:1 [W] UnnecessaryStringOutput: `= "..."` should be rewritten as `...`
```
I am running haml-linter like this:
```
bundle exec haml-lint -c .haml-lint.yml app/views/
```
and in config I have:
```yaml   
UnnecessaryStringOutput:
    enabled: true
    exclude:
      - '**/*.js.haml'
```
and I am still getting this warning.
Big thanks for your help!

**Comment by sds** [comment]
Hey @gajmar,

Unless you're leaving something out, both your configs look incorrect. The first should look like:

```yaml
linters:
  UnnecessaryStringOutput:
    enabled: true
    exclude:
      - '**/*.js.haml'
```

The second should not be nested under `linters`, e.g. it should just be:

```yaml
exclude:
  - '**/*.js.haml'
```

Trying both of these locally works for me.

**Comment by stephen-puiszis** [comment]
I cannot get the global exclusion in my `.haml-lint.yml` configuration file to work for a Rails 4.2 app. My output continues to lint directories and file globs I want to exclude. I have tested a dozen different file-path variants and haven't found anything that has worked. However, I am able to exclude these directories via the CLI.

#### .haml-lint.yml
```yaml
# .haml-lint.yml
# Default application configuration that all configurations inherit from.
#
# This is an opinionated list of which hooks are valuable to run and what their
# out of the box settings should be.

# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: true

exclude:
  - 'app/views/kaminari/**/*'
  - 'app/views/spree/**/*' 

linters:
  AltText:
    enabled: false

# rest of file omitted 
```

#### Relevant parts from Gemfile.lock
```
   haml (4.0.7)
      tilt
    haml-lint (0.13.0)
      haml (~> 4.0)
      rubocop (>= 0.25.0)
      sysexits (~> 1.1)
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
```

**Comment by sds** [comment]
Hey @stephen-puiszis, try switching the name of the gem from `haml-lint` (with a hyphen) to `haml_lint` (with an underscore). We changed the name to follow [proper Rubygems naming conventions](http://guides.rubygems.org/name-your-gem/).

If that doesn't work, I'm not sure what else to offer, as I can successfully exclude files with `exclude` when I test locally (using the same glob patterns as you have above).

**Comment by stephen-puiszis** [comment]
@sds yup that fixed it.  I didn't notice it was underscored, I guess I just assumed b/c the bundle didn't raise any errors and the repo was named `haml-lint` that I had the right one :). Thanks for the help!

**Comment by seanlerner** [comment]
Just in case someone else comes across this issue, note that your options must be lowercase, so:

```
linters:
  LineLength:
    exclude:
      - 'app/views/games/show.html.haml'
```
works (exclude is lowercase), but:
```
linters:
  LineLength:
    Exclude:
      - 'app/views/games/show.html.haml'
```
doesn't work (Exclude is capitalized).
